let products = {
    'shorts': [
        {
            'name': 'ECOTHS BY SPORTIF GO TO SHORT',
            'old_price': '65.00',
            'price': '44.99',
            'quantity': '1',
            'rating': '1',
            'img': ['./src/pr_img/ECOTHS.jpg','./src/pr_img/ECOTHS_back.jpg', './src/pr_img/ECOTHS_front.jpg'],
            'colors': ['blue', 'Khaki Tan ', 'Olive'],
            'colors_data': ['black', 'blue', 'green'],
            'colors2':
                ['./src/img_colors/Nautiluswebp.webp',
                 './src/img_colors/naturalwebp.webp',
                 './src/img_colors/olivinewebp.webp',],
            'size': ['SML', 'MED', 'LRG', 'Xl', 'XLL'],
            'unable_size': [''],
            'product_description': 'The Go To Short is a unique choice for the active adventurer. This versatile short is sustainable, made from a blend of hemp and recycled polyester. Combined, these fibers help reduce water and fossil fuel usage and have a significantly lighter footprint on the earth. Easy on the conscience, but easier still on even the most demanding summer days. Hemp and polyester are strong and durable, yet lightweight and comfortable enough to wear all day long. Paired with just 3% of spandex, this pull-on short features the perfect amount of stretch to keep up with you.',
            'product_details': ['Pull-on styling', 'Full elastic drawstring waist',
                '10" inseam', 'Stretch drawcord',
                'Two slash pockets', 'Single back pocket', 'Sustainable style',
                '53% hemp, 44% recycled polyester, 3% spandex', 'Designed in the USA', 'Made in a Fair Trade Certified™ factory in India']
        },
        {
            'name': 'WEEKENDER TRADER SHORT',
            'old_price': '65.00',
            'price': '40.99',
            'quantity': '1',
            'rating': '3.5',
            'img': ['./src/pr_img/shorts1.jpg'],
            'colors': ['Sand', 'Navy', 'Desert Tan', 'Black', 'White'],
            'colors_data': ['black', 'blue', 'white', 'yellow'],
            'colors2': ['./src/img_colors/Navy.webp','./src/img_colors/DesertTan.webp','./src/img_colors/khakiTan.webp','./src/img_colors/white.webp', './src/img_colors/Black.webp'],
            'size': ['32', '34', '36', '38', '40', '42'],
            'unable_size': ['42'],
            'product_description': 'You don\'t have to "trade" looks for comfort. Constructed from a sturdy twill with a back elastic waistband, these 6" inseam shorts are built with durability and comfort in mind.',
            'product_details': ['Deep front slash pockets', 'Front hook and loop cargo pockets', 'Secure hook and loop back pockets', 'Comfortable back elastic waistband', 'Reinforced stress points', 'Tunnel belt loops', '6" inseam', '60% cotton, 40% polyester, color Chambray 100% Cotton', 'Machine wash', 'Imported',
            ]
        },
        {
            'name': 'ECOTHS BY SPORTIF HYBRID SHORT',
            'old_price': '65.00',
            'price': '39.99',
            'quantity': '1',
            'rating': '4.2',
            'img': ['./src/pr_img/shorts2.jpg','./src/pr_img/shorts2_1.jpg', './src/pr_img/shorts2_2.jpg','./src/pr_img/shorts2_3.jpg'],
            'colors': ['Black', 'White'],
            'colors_data': ['black', 'white'],
            'colors2': ['./src/img_colors/white.webp', './src/img_colors/Black.webp'],
            'size': ['SML', 'MED', 'LRG', 'XL', 'XXL'],
            'unable_size': ['SML'],
            'product_description': 'You don\'t have to "trade" looks for comfort. Constructed from a sturdy twill with a back elastic waistband, these 6" inseam shorts are built with durability and comfort in mind.',
            'product_details': ['Deep front slash pockets', 'Front hook and loop cargo pockets', 'Secure hook and loop back pockets', 'Comfortable back elastic waistband', 'Reinforced stress points', 'Tunnel belt loops', '6" inseam', '60% cotton, 40% polyester, color Chambray 100% Cotton', 'Machine wash', 'Imported',
            ]
        },
        {
            'name': 'HOOK & TACKLE BEER CAN ISLAND® CARGO SHORT',
            'price': '50.00',
            'quantity': '1',
            'rating': '4.5',
            'img': ['./src/pr_img/short_gakgu.jpg'],
            'colors': ['Khaki Tan', 'Olive', 'blue'],
            'colors_data': ['black', 'blue', 'green'],
            'colors2': ['./src/img_colors/khakiTan.webp', './src/img_colors/olivewebp.webp',],
            'size': ['32', '34', '36', '38', '40', '42'],
            'unable_size': ['34'],
            'product_description': 'The same 100% rugged Cotton Camp Cloth as the Island Shorts by Hook & Tackle but in an 8" inseam cargo style short. Features comfort side elastic waistband with handy D-ring, and pockets galore: deep expandable front pockets, front cargo flap pockets, beverage can/phone pocket, hidden security pocket and secure zip back pockets.',
            'product_details': ['Comfort side elastic waistband', 'Deep expandable front pockets',
                'Front cargo flap pockets', 'Beverage can/utility/cell phone pocket',
                'Secure zip back pocket</li', 'Handy D-ring', '8" inseam',
                '100% Cotton', 'Machine wash', 'Imported']
        },
        {
            'name': 'SPORTIF\'S ORIGINAL SHORT',
            'price': '70.00',
            'quantity': '1',
            'rating': '4.8',
            'img': ['./src/pr_img/short5.jpg', './src/pr_img/short5_1.jpg'],
            'colors': ['Khaki Tan', 'blue', 'Black'],
            'colors_data': ['black', 'yellow', 'blue'],
            'colors2': ['./src/img_colors/khaki1.jpg', './src/img_colors/navy1.jpg', './src/img_colors/black1.jpg'],
            'size': ['32', '34', '36', '38', '40', '42'],
            'unable_size': ['32'],
            'product_description': 'With its classic design, practical features and unequaled comfort - it\'s no wonder Sportif \'Original\' stretch cargo shorts are practically the uniform on yachts worldwide! A customer favorite for over 50 years, they\'re called the world\'s best boating shorts. Featuring a 4" inseam for sizes 30-40 and 5.5" inseam for sizes 42-46.',
            'product_details': ['Comfort side elastic waistband', 'Deep expandable front pockets',
                'Front cargo flap pockets', 'Beverage can/utility/cell phone pocket',
                'Secure zip back pocket</li', 'Handy D-ring', '8" inseam',
                '100% Cotton', 'Machine wash', 'Imported']
        },
        {
            'name': 'SPORTIF\'S HATTERAS SHORT',
            'price': '75.00',
            'quantity': '1',
            'rating': '4.8',
            'img': ['./src/pr_img/short6.jpg', './src/pr_img/short6_1.jpg', './src/pr_img/short6_2.jpg'],
            'colors': ['Khaki Tan', 'blue', 'Black'],
            'colors_data': ['black', 'yellow', 'blue'],
            'colors2': ['./src/img_colors/khaki1.jpg', './src/img_colors/navy1.jpg', './src/img_colors/black1.jpg'],
            'size': ['32', '34', '36', '38', '40', '42'],
            'unable_size': ['32'],
            'product_description': 'The Hatteras cargo shorts feature the same great design as our bestselling Sportif Original cargo shorts, but feature a longer 7.5" inseam in a lighter tropical weight fabric.',
            'product_details': ['Comfort side elastic waistband', 'Deep expandable front pockets',
                'Front cargo flap pockets', 'Beverage can/utility/cell phone pocket',
                'Secure zip back pocket</li', 'Handy D-ring', '8" inseam',
                '100% Cotton', 'Machine wash', 'Imported']
        },
        {
            'name': 'SPORTIF\'S TIDEWATER SHORT',
            'price': '75.00',
            'quantity': '1',
            'rating': '4.8',
            'img': ['./src/pr_img/short7.jpg', './src/pr_img/short7_1.jpg', './src/pr_img/short7_2.jpg'],
            'colors': ['Khaki Tan', 'blue', 'Black'],
            'colors_data': ['black', 'yellow', 'blue'],
            'colors2': ['./src/img_colors/khaki1.jpg', './src/img_colors/navy1.jpg', './src/img_colors/black1.jpg'],
            'size': ['32', '34', '36', '38', '40', '42'],
            'unable_size': ['32'],
            'product_description': 'The Hatteras cargo shorts feature the same great design as our bestselling Sportif Original cargo shorts, but feature a longer 7.5" inseam in a lighter tropical weight fabric.',
            'product_details': ['Comfort side elastic waistband', 'Deep expandable front pockets',
                'Front cargo flap pockets', 'Beverage can/utility/cell phone pocket',
                'Secure zip back pocket</li', 'Handy D-ring', '8" inseam',
                '100% Cotton', 'Machine wash', 'Imported']
        },
        {
            'name': 'SPORTIF\'S LAUDERDALE SHORT',
            'price': '72.00',
            'quantity': '1',
            'rating': '4',
            'img': ['./src/pr_img/short8.jpg', './src/pr_img/short8_1.jpg', './src/pr_img/short8_2.jpg', './src/pr_img/short8_3.jpg'],
            'colors': ['Khaki Tan', 'blue', 'Black'],
            'colors_data': ['black', 'yellow', 'blue'],
            'colors2': ['./src/img_colors/khaki1.jpg', './src/img_colors/navy1.jpg', './src/img_colors/black1.jpg'],
            'size': ['32', '34', '36', '38', '40', '42'],
            'unable_size': [''],
            'product_description': 'The Lauderdale Stretch Cargo Shorts have the same great design as our bestselling Sportif Original Cargo Shorts, but in a lighter tropical weight stretch twill fabric that will keep you cool and comfortable in the hottest of climates. Featuring a 4" inseam for sizes 30-40 and 5.5" inseam for sizes 42-46.',
            'product_details': ['Comfort side elastic waistband', 'Deep expandable front pockets',
                'Front cargo flap pockets', 'Beverage can/utility/cell phone pocket',
                'Secure zip back pocket</li', 'Handy D-ring', '8" inseam',
                '100% Cotton', 'Machine wash', 'Imported']
        },
        {
            'name': 'GALAPAGOS PLAIN SHORT',
            'old_price': '69.00',
            'price': '40.99',
            'quantity': '1',
            'rating': '4.5',
            'img': ['./src/pr_img/short9.jpg', './src/pr_img/short9_1.jpg', './src/pr_img/short9_2.jpg'],
            'colors': [ 'Black', 'Khaki Tan'],
            'colors_data': ['black', 'blue'],
            'colors2': ['./src/img_colors/black1.jpg', './src/img_colors/navy1.jpg'],
            'size': ['30', '32', '34', '36', '38', '40', '42'],
            'unable_size': ['32', '34', '36', '38', '40', '42'],
            'product_description': 'The Galapagos 8" inseam stretch shorts are crafted from a lightweight tropical stretch twill that makes all the difference in comfort and freedom of movement in any weather.',
            'product_details': ['Comfort side elastic waistband', 'Deep expandable front pockets',
                'Front cargo flap pockets', 'Beverage can/utility/cell phone pocket',
                'Secure zip back pocket</li', 'Handy D-ring', '8" inseam',
                '100% Cotton', 'Machine wash', 'Imported']
        },
        {
            'name': 'GALAPAGOS PLAIN SHORT',
            'old_price': '40.00',
            'price': '29.99',
            'quantity': '1',
            'rating': '4',
            'img': ['./src/pr_img/short10.jpg'],
            'colors': ['Chambray', 'Khaki Tan'],
            'colors_data': ['blue'],
            'colors2': ['./src/img_colors/chambray.jpg'],
            'size': ['30', '32', '34', '36', '38', '40', '42'],
            'unable_size': ['32'],
            'product_description': 'The Galapagos 8" inseam stretch shorts are crafted from a lightweight tropical stretch twill that makes all the difference in comfort and freedom of movement in any weather.',
            'product_details': ['Comfort side elastic waistband', 'Deep expandable front pockets',
                'Front cargo flap pockets', 'Beverage can/utility/cell phone pocket',
                'Secure zip back pocket</li', 'Handy D-ring', '8" inseam',
                '100% Cotton', 'Machine wash', 'Imported']
        },
        {
            'name': 'ECOTHS BY SPORTIF GO TO SHORT(COPIED)',
            'old_price': '65.00',
            'price': '44.99',
            'quantity': '1',
            'rating': '1',
            'img': ['./src/pr_img/ECOTHS.jpg','./src/pr_img/ECOTHS_back.jpg', './src/pr_img/ECOTHS_front.jpg'],
            'colors': ['blue', 'Khaki Tan ', 'Olive'],
            'colors_data': ['black', 'blue', 'green'],
            'colors2':
                ['./src/img_colors/Nautiluswebp.webp',
                 './src/img_colors/naturalwebp.webp',
                 './src/img_colors/olivinewebp.webp',],
            'size': ['SML', 'MED', 'LRG', 'Xl', 'XLL'],
            'unable_size': [''],
            'product_description': 'The Go To Short is a unique choice for the active adventurer. This versatile short is sustainable, made from a blend of hemp and recycled polyester. Combined, these fibers help reduce water and fossil fuel usage and have a significantly lighter footprint on the earth. Easy on the conscience, but easier still on even the most demanding summer days. Hemp and polyester are strong and durable, yet lightweight and comfortable enough to wear all day long. Paired with just 3% of spandex, this pull-on short features the perfect amount of stretch to keep up with you.',
            'product_details': ['Pull-on styling', 'Full elastic drawstring waist',
                '10" inseam', 'Stretch drawcord',
                'Two slash pockets', 'Single back pocket', 'Sustainable style',
                '53% hemp, 44% recycled polyester, 3% spandex', 'Designed in the USA', 'Made in a Fair Trade Certified™ factory in India']
        },
        {
            'name': 'WEEKENDER TRADER SHORT(COPIED)',
            'old_price': '65.00',
            'price': '40.99',
            'quantity': '1',
            'rating': '3.5',
            'img': ['./src/pr_img/shorts1.jpg'],
            'colors': ['Sand', 'Navy', 'Desert Tan', 'Black', 'White'],
            'colors_data': ['black', 'blue', 'white', 'yellow'],
            'colors2': ['./src/img_colors/Navy.webp','./src/img_colors/DesertTan.webp','./src/img_colors/khakiTan.webp','./src/img_colors/white.webp', './src/img_colors/Black.webp'],
            'size': ['32', '34', '36', '38', '40', '42'],
            'unable_size': ['42'],
            'product_description': 'You don\'t have to "trade" looks for comfort. Constructed from a sturdy twill with a back elastic waistband, these 6" inseam shorts are built with durability and comfort in mind.',
            'product_details': ['Deep front slash pockets', 'Front hook and loop cargo pockets', 'Secure hook and loop back pockets', 'Comfortable back elastic waistband', 'Reinforced stress points', 'Tunnel belt loops', '6" inseam', '60% cotton, 40% polyester, color Chambray 100% Cotton', 'Machine wash', 'Imported',
            ]
        },
        {
            'name': 'ECOTHS BY SPORTIF HYBRID SHORT(COPIED)',
            'old_price': '65.00',
            'price': '39.99',
            'quantity': '1',
            'rating': '4.2',
            'img': ['./src/pr_img/shorts2.jpg','./src/pr_img/shorts2_1.jpg', './src/pr_img/shorts2_2.jpg','./src/pr_img/shorts2_3.jpg'],
            'colors': ['Black', 'White'],
            'colors_data': ['black', 'white'],
            'colors2': ['./src/img_colors/white.webp', './src/img_colors/Black.webp'],
            'size': ['SML', 'MED', 'LRG', 'XL', 'XXL'],
            'unable_size': ['SML'],
            'product_description': 'You don\'t have to "trade" looks for comfort. Constructed from a sturdy twill with a back elastic waistband, these 6" inseam shorts are built with durability and comfort in mind.',
            'product_details': ['Deep front slash pockets', 'Front hook and loop cargo pockets', 'Secure hook and loop back pockets', 'Comfortable back elastic waistband', 'Reinforced stress points', 'Tunnel belt loops', '6" inseam', '60% cotton, 40% polyester, color Chambray 100% Cotton', 'Machine wash', 'Imported',
            ]
        },
        {
            'name': 'HOOK & TACKLE BEER CAN ISLAND® CARGO SHORT(COPIED)',
            'price': '50.00',
            'quantity': '1',
            'rating': '4.5',
            'img': ['./src/pr_img/short_gakgu.jpg'],
            'colors': ['Khaki Tan', 'Olive', 'blue'],
            'colors_data': ['black', 'blue', 'green'],
            'colors2': ['./src/img_colors/khakiTan.webp', './src/img_colors/olivewebp.webp',],
            'size': ['32', '34', '36', '38', '40', '42'],
            'unable_size': ['34'],
            'product_description': 'The same 100% rugged Cotton Camp Cloth as the Island Shorts by Hook & Tackle but in an 8" inseam cargo style short. Features comfort side elastic waistband with handy D-ring, and pockets galore: deep expandable front pockets, front cargo flap pockets, beverage can/phone pocket, hidden security pocket and secure zip back pockets.',
            'product_details': ['Comfort side elastic waistband', 'Deep expandable front pockets',
                'Front cargo flap pockets', 'Beverage can/utility/cell phone pocket',
                'Secure zip back pocket</li', 'Handy D-ring', '8" inseam',
                '100% Cotton', 'Machine wash', 'Imported']
        },
        {
            'name': 'SPORTIF\'S ORIGINAL SHORT(COPIED)',
            'price': '70.00',
            'quantity': '1',
            'rating': '4.8',
            'img': ['./src/pr_img/short5.jpg', './src/pr_img/short5_1.jpg'],
            'colors': ['Khaki Tan', 'blue', 'Black'],
            'colors_data': ['black', 'yellow', 'blue'],
            'colors2': ['./src/img_colors/khaki1.jpg', './src/img_colors/navy1.jpg', './src/img_colors/black1.jpg'],
            'size': ['32', '34', '36', '38', '40', '42'],
            'unable_size': ['32'],
            'product_description': 'With its classic design, practical features and unequaled comfort - it\'s no wonder Sportif \'Original\' stretch cargo shorts are practically the uniform on yachts worldwide! A customer favorite for over 50 years, they\'re called the world\'s best boating shorts. Featuring a 4" inseam for sizes 30-40 and 5.5" inseam for sizes 42-46.',
            'product_details': ['Comfort side elastic waistband', 'Deep expandable front pockets',
                'Front cargo flap pockets', 'Beverage can/utility/cell phone pocket',
                'Secure zip back pocket</li', 'Handy D-ring', '8" inseam',
                '100% Cotton', 'Machine wash', 'Imported']
        },
        {
            'name': 'SPORTIF\'S HATTERAS SHORT(COPIED)',
            'price': '75.00',
            'quantity': '1',
            'rating': '4.8',
            'img': ['./src/pr_img/short6.jpg', './src/pr_img/short6_1.jpg', './src/pr_img/short6_2.jpg'],
            'colors': ['Khaki Tan', 'blue', 'Black'],
            'colors_data': ['black', 'yellow', 'blue'],
            'colors2': ['./src/img_colors/khaki1.jpg', './src/img_colors/navy1.jpg', './src/img_colors/black1.jpg'],
            'size': ['32', '34', '36', '38', '40', '42'],
            'unable_size': ['32'],
            'product_description': 'The Hatteras cargo shorts feature the same great design as our bestselling Sportif Original cargo shorts, but feature a longer 7.5" inseam in a lighter tropical weight fabric.',
            'product_details': ['Comfort side elastic waistband', 'Deep expandable front pockets',
                'Front cargo flap pockets', 'Beverage can/utility/cell phone pocket',
                'Secure zip back pocket</li', 'Handy D-ring', '8" inseam',
                '100% Cotton', 'Machine wash', 'Imported']
        },
        {
            'name': 'SPORTIF\'S TIDEWATER SHORT(COPIED)',
            'price': '75.00',
            'quantity': '1',
            'rating': '4.8',
            'img': ['./src/pr_img/short7.jpg', './src/pr_img/short7_1.jpg', './src/pr_img/short7_2.jpg'],
            'colors': ['Khaki Tan', 'blue', 'Black'],
            'colors_data': ['black', 'yellow', 'blue'],
            'colors2': ['./src/img_colors/khaki1.jpg', './src/img_colors/navy1.jpg', './src/img_colors/black1.jpg'],
            'size': ['32', '34', '36', '38', '40', '42'],
            'unable_size': ['32'],
            'product_description': 'The Hatteras cargo shorts feature the same great design as our bestselling Sportif Original cargo shorts, but feature a longer 7.5" inseam in a lighter tropical weight fabric.',
            'product_details': ['Comfort side elastic waistband', 'Deep expandable front pockets',
                'Front cargo flap pockets', 'Beverage can/utility/cell phone pocket',
                'Secure zip back pocket</li', 'Handy D-ring', '8" inseam',
                '100% Cotton', 'Machine wash', 'Imported']
        },
        {
            'name': 'SPORTIF\'S LAUDERDALE SHORT(COPIED)',
            'price': '72.00',
            'quantity': '1',
            'rating': '4',
            'img': ['./src/pr_img/short8.jpg', './src/pr_img/short8_1.jpg', './src/pr_img/short8_2.jpg', './src/pr_img/short8_3.jpg'],
            'colors': ['Khaki Tan', 'blue', 'Black'],
            'colors_data': ['black', 'yellow', 'blue'],
            'colors2': ['./src/img_colors/khaki1.jpg', './src/img_colors/navy1.jpg', './src/img_colors/black1.jpg'],
            'size': ['32', '34', '36', '38', '40', '42'],
            'unable_size': [''],
            'product_description': 'The Lauderdale Stretch Cargo Shorts have the same great design as our bestselling Sportif Original Cargo Shorts, but in a lighter tropical weight stretch twill fabric that will keep you cool and comfortable in the hottest of climates. Featuring a 4" inseam for sizes 30-40 and 5.5" inseam for sizes 42-46.',
            'product_details': ['Comfort side elastic waistband', 'Deep expandable front pockets',
                'Front cargo flap pockets', 'Beverage can/utility/cell phone pocket',
                'Secure zip back pocket</li', 'Handy D-ring', '8" inseam',
                '100% Cotton', 'Machine wash', 'Imported']
        },
        {
            'name': 'GALAPAGOS PLAIN SHORT(COPIED)',
            'old_price': '69.00',
            'price': '40.99',
            'quantity': '1',
            'rating': '4.5',
            'img': ['./src/pr_img/short9.jpg', './src/pr_img/short9_1.jpg', './src/pr_img/short9_2.jpg'],
            'colors': [ 'Black', 'Khaki Tan'],
            'colors_data': ['black', 'blue'],
            'colors2': ['./src/img_colors/black1.jpg', './src/img_colors/navy1.jpg'],
            'size': ['30', '32', '34', '36', '38', '40', '42'],
            'unable_size': ['32', '34', '36', '38', '40', '42'],
            'product_description': 'The Galapagos 8" inseam stretch shorts are crafted from a lightweight tropical stretch twill that makes all the difference in comfort and freedom of movement in any weather.',
            'product_details': ['Comfort side elastic waistband', 'Deep expandable front pockets',
                'Front cargo flap pockets', 'Beverage can/utility/cell phone pocket',
                'Secure zip back pocket</li', 'Handy D-ring', '8" inseam',
                '100% Cotton', 'Machine wash', 'Imported']
        },
        {
            'name': 'GALAPAGOS PLAIN SHORT(COPIED)',
            'old_price': '40.00',
            'price': '29.99',
            'quantity': '1',
            'rating': '4',
            'img': ['./src/pr_img/short10.jpg'],
            'colors': ['Chambray', 'Khaki Tan'],
            'colors_data': ['blue'],
            'colors2': ['./src/img_colors/chambray.jpg'],
            'size': ['30', '32', '34', '36', '38', '40', '42'],
            'unable_size': ['32'],
            'product_description': 'The Galapagos 8" inseam stretch shorts are crafted from a lightweight tropical stretch twill that makes all the difference in comfort and freedom of movement in any weather.',
            'product_details': ['Comfort side elastic waistband', 'Deep expandable front pockets',
                'Front cargo flap pockets', 'Beverage can/utility/cell phone pocket',
                'Secure zip back pocket</li', 'Handy D-ring', '8" inseam',
                '100% Cotton', 'Machine wash', 'Imported']
        },
    ],
    'pants': [
        {
            'name': 'SPORTIF\'S ORIGINAL PANT',
            'price': '94.00',
            'quantity': '1',
            'rating': '4.5',
            'img': ['./src/pr_img/pants1.webp', './src/pr_img/pants1_1.jpg'],
            'colors': ['Khaki Tan', 'Navy', 'Desert Tan', 'Black'],
            'colors_data': ['black', 'blue', 'white'],
            'colors2': ['./src/img_colors/Navy.webp','./src/img_colors/DesertTan.webp','./src/img_colors/khakiTan.webp','./src/img_colors/Black.webp'],
            'size': ['28', '30', '32', '34', '36', '38', '40', '42', '44', '46'],
            'unable_size': ['28'],
            'product_description': 'These classic nautical cargo pants are built to last and designed to exceed your expectations. Crafted from our stretch twill blend that offers the comfort of cotton, the wrinkle resistance of polyester and the mobility of spandex.',
            'product_details': ['Constructed from our 7.5 oz. Mid-Weight Stretch Twill fabric', 'Exclusive 7-pocket design includes two deep front pockets, two front cargo pockets with button-through flap closure, and two zippered security back pockets', 'Bonus pocket inside the right front pocket is perfect for carrying a small cell phone or pocket knife', 'Non-roll stretch waistband', 'Sturdy tunnel belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', '62% polyester, 35% cotton, 3% spandex blend is travel-friendly and ready to wear straight from the dryer', 'Machine wash', 'Imported']
        },
        {
            'name': 'ECOTHS BY SPORTIF CHAMBERS PAJAMA PANT',
            'price': '29.99',
            'quantity': '1',
            'rating': '4',
            'img': ['./src/pr_img/pants2.jpg', './src/pr_img/pants2_2.jpg', './src/pr_img/pants2_3.jpg', './src/pr_img/pants2_4.jpg'],
            'colors': ['Red', 'Midnight'],
            'colors_data': ['red'],
            'colors2': ['./src/img_colors/Red.webp','./src/img_colors/Midnight.webp'],
            'size': ['SML', 'MED', 'LRG', 'XL', 'XXL'],
            'unable_size': ['SML', 'MED'],
            'product_description': 'Known for bringing you comfort, Ecoths delivers again with the Chambers PJ Pant. These pants are made from 100% cotton, creating a soft-yet-tough flannel that will help regulate your temperature at night, while delivering hypoallergenic comfort. These classic pull-on PJs are secured with an elastic waist and drawcord and feature Buffalo check print reminiscent of winter trips to the cabin. It\'s time to get cozy!',
            'product_details': ['Classic pull on pajama pant', 'Elastic waist with drawcord', '31" inseam', 'Checkered print fabric', '100% Cotton flannel', 'Machine wash cold, tumble dry low, warm iron', 'Designed in the USA', 'Made in a Fair Trade Certified™ factory in India',],
        },
        {
            'name': 'SPORTIF\'S CALCUTTA PLEATED CHINOS',
            'old_price': '94.00',
            'price': '69.99',
            'quantity': '1',
            'rating': '5',
            'img': ['./src/pr_img/pants3.jpg'],
            'colors': ['Navy', 'Desert Tan', 'Khaki Tan', 'Black'],
            'colors_data': ['black', 'blue', 'white'],
            'colors2': ['./src/img_colors/Navy.webp','./src/img_colors/DesertTan.webp','./src/img_colors/khakiTan.webp','./src/img_colors/Black.webp'],
            'size': ['30', '32', '34', '36', '38', '40', '42', '44', '46'],
            'unable_size': ['42', '44', '46'],
            'product_description': 'The Calcutta chinos are crafted from a lightweight tropical stretch fabric to keep you cool and comfortable in the hottest of climates.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
        },
        {
            'name': 'SPORTIF\'S TRINIDAD PLEATED CHINOS',
            'old_price': '94.00',
            'price': '69.99',
            'quantity': '1',
            'rating': '4',
            'img': ['./src/pr_img/pants4.webp'],
            'colors': ['Navy', 'Desert Tan', 'Khaki Tan'],
            'colors_data': ['black', 'blue', 'white'],
            'colors2': ['./src/img_colors/Navy.webp','./src/img_colors/DesertTan.webp','./src/img_colors/khakiTan.webp'],
            'size': ['30', '32', '34', '36', '38', '40', '42', '44', '46'],
            'unable_size': ['42', '44', '46'],
            'product_description': 'The Calcutta chinos are crafted from a lightweight tropical stretch fabric to keep you cool and comfortable in the hottest of climates.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'SPORTIF\'S TRINIDAD CHINOS',
            'old_price': '94.00',
            'price': '69.99',
            'quantity': '1',
            'rating': '4',
            'img': ['./src/pr_img/pants5.webp'],
            'colors': ['Navy', 'Desert Tan', 'Khaki Tan'],
            'colors_data': ['black', 'blue', 'white'],
            'colors2': ['./src/img_colors/Navy.webp','./src/img_colors/DesertTan.webp','./src/img_colors/khakiTan.webp'],
            'size': ['30', '32', '34', '36', '38', '40', '42', '44', '46'],
            'unable_size': ['42', '38', '40'],
            'product_description': 'The Calcutta chinos are crafted from a lightweight tropical stretch fabric to keep you cool and comfortable in the hottest of climates.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
    ],
    'shirts': [
        {
            'name': 'REYN SPOONER SUMMER COMMEMORATIVE 2022',
            // 'old_price': '94.00',
            'price': '120.00',
            'quantity': '1',
            'rating': '4.7',
            'img': ['./src/pr_img/shirt1.jpg'],
            'colors': ['Natural', 'Navy'],
            'colors_data': ['white', 'blue'],
            'colors2': ['./src/img_colors/Natural.jpg','./src/img_colors/Navy_shirt.jpg'],
            'size': ['MED', 'LRG', 'XL', 'XXL'],
            'unable_size': ['LRG'],
            'product_description': 'Island getaway: here we come! The Reyn Spooner Summer Commemorative Print Shirt is a fun way to bring the celebration to every day. Warm weather will feel better with a breathable, wrinkle-free blend of cotton and spun poly–Reyn Spooner\'s signature Spooner Kloth™. Split 55 cotton and 45 polyester, this top manages moisture and temperature very well. Flowers, palm trees, and calming waters play alongside classic details, including a full button front, collar, and chest pocket. The relaxed fit continues the laid-back personality of this top.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'HOOK & TACKLE SEACLIFF 2.0 SHORT SLEEVE SHIRT',
            // 'old_price': '94.00',
            'price': '55.00',
            'quantity': '1',
            'rating': '4.2',
            'img': ['./src/pr_img/shirt2.jpg'],
            'colors': ['Aqua', 'Coral', 'White'],
            'colors_data': ['blue', 'orange', 'white'],
            'colors2': ['./src/img_colors/blue1.jpg','./src/img_colors/red.jpg','./src/img_colors/white.webp'],
            'size': ['MED', 'LRG', 'XL', 'XXL'],
            'unable_size': [''],
            'product_description': 'The only concern you should have on a fishing trip is whether or not you reel in the big ones, so let the Hook & Tackle Seacliff 2.0 Short Sleeve Shirt handle the rest. Built for fishing, but great for any outdoor activity in warm weather, this top stands above the rest because of its unique fabric and storage. The tear- and stain-resistant microfiber rip-stop fabric is lightweight, quick-drying, and features the highest possible sun protection rating of UPF 50+. Pockets, secured with both zippers and snap, and a fly rod utility loop are perfect accessories for fishing. Vents and a moisture-wicking mesh lining top off this shirt\'s list of benefits and will aid in keeping you cool.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'ECOTHS BY SPORTIF PARADISE SHIRT',
            'old_price': '49.00',
            'price': '29.99',
            'quantity': '1',
            'rating': '4',
            'img': ['./src/pr_img/shirt3.jpg', './src/pr_img/shirt3_1.jpg', './src/pr_img/shirt3_2.jpg', './src/pr_img/shirt3_3.jpg'],
            'colors': ['Blue Palma', 'White Palma'],
            'colors_data': ['blue', 'white'],
            'colors2': ['./src/img_colors/blue_palma.jpg','./src/img_colors/white_palma.jpg'],
            'size': ['SML', 'MED', 'LRG', 'XL', 'XXL'],
            'unable_size': ['SML'],
            'product_description': 'The Paradise Shirt is whimsical choice for days you wish you were on vacation. This short sleeve shirt is woven from summer\'s favorite fiber: 100% cotton. This excellent choice grants the shirt lightness, breathability, and temperature regulation. Classic details, such as a button-down collar, brown horn buttons, and a reinforced breast pocket with a pen (or sunglass) pocket, peacefully play alongside tropical prints. Details, such as a locker loop, pleat along the back yoke, and chambray facing on the inside collar band, piped with checked plaid poplin, polish the shirt. With a time-honored shape and convenient features, this is the choice for your urban escapades.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'RJC PARADISE BLOCK PRINT SHIRT',
            'old_price': '49.00',
            'price': '29.99',
            'quantity': '1',
            'rating': '4',
            'img': ['./src/pr_img/shirt4.jpg'],
            'colors': ['Wine'],
            'colors_data': ['red'],
            'colors2': ['./src/img_colors/wine.jpg'],
            'size': ['SML', 'MED', 'LRG', 'XL'],
            'unable_size': ['MED', 'LRG', 'XL'],
            'product_description': 'This bold print showcases palms and unique patterns for a distinctively tropical and traditional aloha look and feel. This American made shirt has a full button front with a relaxed open collar, pattern-matched pocket, and a straight hem.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'RJC OCEAN FRONT PRINT SHIRT',
            'old_price': '49.00',
            'price': '29.99',
            'quantity': '1',
            'rating': '3',
            'img': ['./src/pr_img/shirt5.jpg'],
            'colors': ['Teal'],
            'colors_data': ['blue'],
            'colors2': ['./src/img_colors/teal.jpg'],
            'size': ['SML', 'MED', 'LRG', 'XL'],
            'unable_size': ['MED', 'LRG', 'XL'],
            'product_description': 'One look at this print and you can almost smell the sweet fragrance of the island and feel the ocean breeze through your hair. This serene print shirt has just enough tropical style and tradition to get you in a blissful state of mind. Enjoy the splendor and majesty Mother Nature has to offer in this exceptionally comfortable print shirt. This American made shirt has a full button front with a relaxed open collar, pattern-matched chest pocket, and a straight hem.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'RJC ISLAND LIFE PRINT SHIRT',
            'old_price': '49.00',
            'price': '29.99',
            'quantity': '1',
            'rating': '4',
            'img': ['./src/pr_img/shirt6.jpg'],
            'colors': ['Burgundy'],
            'colors_data': ['red', 'white'],
            'colors2': ['./src/img_colors/burgrundy.jpg'],
            'size': ['SML', 'MED', 'LRG', 'XL'],
            'unable_size': ['LRG', 'XL'],
            'product_description': 'You\'ll instantly feel energized in this bold and playful shirt. Truly a tropical print and traditional aloha styling that will make you look great at your next big outing or luau. This American made shirt has a full button front with open collar, pattern-matched chest pocket and straight hem.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'GO BAREFOOT MINI TAHITIAN PRINT SHIRT',
            // 'old_price': '49.00',
            'price': '89.99',
            'quantity': '1',
            'rating': '5',
            'img': ['./src/pr_img/shirt7.jpg'],
            'colors': ['Navy'],
            'colors_data': ['blue'],
            'colors2': ['./src/img_colors/navy.jpg'],
            'size': ['MED', 'LRG', 'XL'],
            'unable_size': [],
            'product_description': 'A cool white ribbon of hibiscus flowers snakes its way across this relaxed, cotton shirt. One look at this tranquil floral print and your mind will drift away to a place with warm sand, fragrant breezes and the distant sound of a ukulele. A perfect match for shorts, denim, or chinos. Full button front placket, pattern-matched chest pocket, straight hem and side vents for ease of movement.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'HOOK & TACKLE SEACLIFF 2.0 LONG SLEEVE SHIRT',
            // 'old_price': '49.00',
            'price': '65.00',
            'quantity': '1',
            'rating': '3',
            'img': ['./src/pr_img/shirt8.jpg', './src/pr_img/shirt8_1.jpg'],
            'colors': ['Sky blue', 'White'],
            'colors_data': ['blue', 'white'],
            'colors2': ['./src/img_colors/sky_blue.jpg', './src/img_colors/white8.webp'],
            'size': ['MED', 'LRG', 'XL', 'XXL'],
            'unable_size': [],
            'product_description': 'Crafted from lightweight polyester with practical details and classic styling, this shirt offers so many features. UPF 50+ sun protection, vented back with moisture-wicking mesh lining and roll-up sleeves with tabs make this one of the coolest shirts around. Other features are a hidden button-down collar, secured snap and zippered pockets, and a fly/utility loop.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'REYN SPOONER SUMMER COMMEMORATIVE 2022(COPIED)',
            // 'old_price': '94.00',
            'price': '120.00',
            'quantity': '1',
            'rating': '4.7',
            'img': ['./src/pr_img/shirt1.jpg'],
            'colors': ['Natural', 'Navy'],
            'colors_data': ['white', 'blue'],
            'colors2': ['./src/img_colors/Natural.jpg','./src/img_colors/Navy_shirt.jpg'],
            'size': ['MED', 'LRG', 'XL', 'XXL'],
            'unable_size': ['LRG'],
            'product_description': 'Island getaway: here we come! The Reyn Spooner Summer Commemorative Print Shirt is a fun way to bring the celebration to every day. Warm weather will feel better with a breathable, wrinkle-free blend of cotton and spun poly–Reyn Spooner\'s signature Spooner Kloth™. Split 55 cotton and 45 polyester, this top manages moisture and temperature very well. Flowers, palm trees, and calming waters play alongside classic details, including a full button front, collar, and chest pocket. The relaxed fit continues the laid-back personality of this top.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'HOOK & TACKLE SEACLIFF 2.0 SHORT SLEEVE SHIRT(COPIED)',
            // 'old_price': '94.00',
            'price': '55.00',
            'quantity': '1',
            'rating': '4.2',
            'img': ['./src/pr_img/shirt2.jpg'],
            'colors': ['Aqua', 'Coral', 'White'],
            'colors_data': ['blue', 'orange', 'white'],
            'colors2': ['./src/img_colors/blue1.jpg','./src/img_colors/red.jpg','./src/img_colors/white.webp'],
            'size': ['MED', 'LRG', 'XL', 'XXL'],
            'unable_size': [''],
            'product_description': 'The only concern you should have on a fishing trip is whether or not you reel in the big ones, so let the Hook & Tackle Seacliff 2.0 Short Sleeve Shirt handle the rest. Built for fishing, but great for any outdoor activity in warm weather, this top stands above the rest because of its unique fabric and storage. The tear- and stain-resistant microfiber rip-stop fabric is lightweight, quick-drying, and features the highest possible sun protection rating of UPF 50+. Pockets, secured with both zippers and snap, and a fly rod utility loop are perfect accessories for fishing. Vents and a moisture-wicking mesh lining top off this shirt\'s list of benefits and will aid in keeping you cool.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'ECOTHS BY SPORTIF PARADISE SHIRT(COPIED)',
            'old_price': '49.00',
            'price': '29.99',
            'quantity': '1',
            'rating': '3.7',
            'img': ['./src/pr_img/shirt3.jpg', './src/pr_img/shirt3_1.jpg', './src/pr_img/shirt3_2.jpg', './src/pr_img/shirt3_3.jpg'],
            'colors': ['Blue Palma', 'White Palma'],
            'colors_data': ['blue', 'white'],
            'colors2': ['./src/img_colors/blue_palma.jpg','./src/img_colors/white_palma.jpg'],
            'size': ['SML', 'MED', 'LRG', 'XL', 'XXL'],
            'unable_size': ['SML'],
            'product_description': 'The Paradise Shirt is whimsical choice for days you wish you were on vacation. This short sleeve shirt is woven from summer\'s favorite fiber: 100% cotton. This excellent choice grants the shirt lightness, breathability, and temperature regulation. Classic details, such as a button-down collar, brown horn buttons, and a reinforced breast pocket with a pen (or sunglass) pocket, peacefully play alongside tropical prints. Details, such as a locker loop, pleat along the back yoke, and chambray facing on the inside collar band, piped with checked plaid poplin, polish the shirt. With a time-honored shape and convenient features, this is the choice for your urban escapades.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'RJC PARADISE BLOCK PRINT SHIRT(COPIED)',
            'old_price': '49.00',
            'price': '29.99',
            'quantity': '1',
            'rating': '5',
            'img': ['./src/pr_img/shirt4.jpg'],
            'colors': ['Wine'],
            'colors_data': ['red'],
            'colors2': ['./src/img_colors/wine.jpg'],
            'size': ['SML', 'MED', 'LRG', 'XL'],
            'unable_size': ['MED', 'LRG', 'XL'],
            'product_description': 'This bold print showcases palms and unique patterns for a distinctively tropical and traditional aloha look and feel. This American made shirt has a full button front with a relaxed open collar, pattern-matched pocket, and a straight hem.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'RJC OCEAN FRONT PRINT SHIRT(COPIED)',
            'old_price': '49.00',
            'price': '29.99',
            'quantity': '1',
            'rating': '3',
            'img': ['./src/pr_img/shirt5.jpg'],
            'colors': ['Teal'],
            'colors_data': ['blue'],
            'colors2': ['./src/img_colors/teal.jpg'],
            'size': ['SML', 'MED', 'LRG', 'XL'],
            'unable_size': ['MED', 'LRG', 'XL'],
            'product_description': 'One look at this print and you can almost smell the sweet fragrance of the island and feel the ocean breeze through your hair. This serene print shirt has just enough tropical style and tradition to get you in a blissful state of mind. Enjoy the splendor and majesty Mother Nature has to offer in this exceptionally comfortable print shirt. This American made shirt has a full button front with a relaxed open collar, pattern-matched chest pocket, and a straight hem.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'RJC ISLAND LIFE PRINT SHIRT(COPIED)',
            'old_price': '49.00',
            'price': '29.99',
            'quantity': '1',
            'rating': '4',
            'img': ['./src/pr_img/shirt6.jpg'],
            'colors': ['Burgundy'],
            'colors_data': ['red', 'white'],
            'colors2': ['./src/img_colors/burgrundy.jpg'],
            'size': ['SML', 'MED', 'LRG', 'XL'],
            'unable_size': ['LRG', 'XL'],
            'product_description': 'You\'ll instantly feel energized in this bold and playful shirt. Truly a tropical print and traditional aloha styling that will make you look great at your next big outing or luau. This American made shirt has a full button front with open collar, pattern-matched chest pocket and straight hem.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'GO BAREFOOT MINI TAHITIAN PRINT SHIRT(COPIED)',
            // 'old_price': '49.00',
            'price': '89.99',
            'quantity': '1',
            'rating': '4',
            'img': ['./src/pr_img/shirt7.jpg'],
            'colors': ['Navy'],
            'colors_data': ['blue'],
            'colors2': ['./src/img_colors/navy.jpg'],
            'size': ['MED', 'LRG', 'XL'],
            'unable_size': [],
            'product_description': 'A cool white ribbon of hibiscus flowers snakes its way across this relaxed, cotton shirt. One look at this tranquil floral print and your mind will drift away to a place with warm sand, fragrant breezes and the distant sound of a ukulele. A perfect match for shorts, denim, or chinos. Full button front placket, pattern-matched chest pocket, straight hem and side vents for ease of movement.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'HOOK & TACKLE SEACLIFF 2.0 LONG SLEEVE SHIRT(COPIED)',
            // 'old_price': '49.00',
            'price': '65.00',
            'quantity': '1',
            'rating': '4',
            'img': ['./src/pr_img/shirt8.jpg', './src/pr_img/shirt8_1.jpg'],
            'colors': ['Sky blue', 'White'],
            'colors_data': ['blue', 'white'],
            'colors2': ['./src/img_colors/sky_blue.jpg', './src/img_colors/white8.webp'],
            'size': ['MED', 'LRG', 'XL', 'XXL'],
            'unable_size': [],
            'product_description': 'Crafted from lightweight polyester with practical details and classic styling, this shirt offers so many features. UPF 50+ sun protection, vented back with moisture-wicking mesh lining and roll-up sleeves with tabs make this one of the coolest shirts around. Other features are a hidden button-down collar, secured snap and zippered pockets, and a fly/utility loop.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
    ],
    'accessories': [
        {
            'name': 'LEATHER TAB BRAIDED BELT',
            // 'old_price': '49.00',
            'price': '32.00',
            'quantity': '1',
            'rating': '4.2',
            'img': ['./src/pr_img/belt1.jpg'],
            'colors': ['Multi Colored'],
            'colors_data': ['black', 'white', 'blue'],
            'colors2': ['./src/img_colors/multi_colored.jpg'],
            'size': ['32', '34', '36', '38', '40', '42', '44', '46',],
            'unable_size': [],
            'product_description': 'This stretch belt is made with comfort in mind. It flexes and stretches with your every move, so it won\'t pinch or bind.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'LEATHER TAB COTTON BELT',
            // 'old_price': '49.00',
            'price': '29.00',
            'quantity': '1',
            'rating': '4.6',
            'img': ['./src/pr_img/belt2.jpg'],
            'colors': ['Khaki Tan', 'Navy', 'White'],
            'colors_data': ['yellow', 'blue', 'white'],
            'colors2': ['./src/img_colors/khakitan.jpg', './src/img_colors/navybelt.jpg', './src/img_colors/whitebelt.jpg' ],
            'size': ['32', '34', '36', '38', '40', '42', '44', '46'],
            'unable_size': ['32', '42'],
            'product_description': 'This stretch belt is made with comfort in mind. It flexes and stretches with your every move so it won\'t pinch or bind.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'ADJUSTABLE TAB BRAIDED BELT',
            // 'old_price': '49.00',
            'price': '35.00',
            'quantity': '1',
            'rating': '4.6',
            'img': ['./src/pr_img/belt3.jpg'],
            'colors': ['Multi-Colored'],
            'colors_data': ['yellow', 'blue', 'green'],
            'colors2': ['./src/img_colors/multi_colored1.jpg'],
            'size': ['32', '34', '36', '38', '40', '42', '44', '46'],
            'unable_size': [''],
            'product_description': 'Never fails. One hole is too loose, the next is too tight. This multi-colored stretch belt splits the difference comfortably. The unique hole-free design of this belt allows you to thread the prong through the braided strap at any point for custom fit.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'ADJUSTABLE TAB BRAIDED BELT',
            // 'old_price': '49.00',
            'price': '19.00',
            'quantity': '1',
            'rating': '4',
            'img': ['./src/pr_img/belt4.jpg'],
            'colors': ['Multi-Colored'],
            'colors_data': ['yellow', 'black', 'blue'],
            'colors2': ['./src/img_colors/black_belt.jpg', './src/img_colors/khakitan1.jpg', './src/img_colors/navy_belt1.jpg', ],
            'size': ['1SZ'],
            'unable_size': [''],
            'product_description': 'This web belt features a travel friendly, easy-to-use, non-metal buckle that adjusts in a snap.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'ADJUSTABLE TAB SOLID COLOR BRAIDED BELT',
            // 'old_price': '49.00',
            'price': '39.00',
            'quantity': '1',
            'rating': '4.5',
            'img': ['./src/pr_img/belt5.jpg'],
            'colors': ['Navy', 'Khaki Tan', 'Black'],
            'colors_data': ['blue', 'yellow', 'black'],
            'colors2': ['./src/img_colors/navy2.jpg', './src/img_colors/khaki2.jpg', './src/img_colors/black2.jpg', ],
            'size': ['32', '34', '36', '38', '40', '42', '44', '46'],
            'unable_size': [''],
            'product_description': 'Never fails. One hole is too loose, the next is too tight. This braided belt has just enough stretch to split the difference.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'THERAPEUTIC COMPRESSION SOCKS',
            // 'old_price': '49.00',
            'price': '30.00',
            'quantity': '1',
            'rating': '4.5',
            'img': ['./src/pr_img/socks6.jpg'],
            'colors': ['Navy', 'Khaki Tan', 'Black'],
            'colors_data': ['blue', 'yellow', 'black'],
            'colors2': ['./src/img_colors/navy6.jpg', './src/img_colors/khaki6.jpg', './src/img_colors/black6.jpg', ],
            'size': ['M/L', 'L/XL'],
            'unable_size': [''],
            'product_description': 'These moderate compression socks will help improve circulation when you need or want extra support in your day at every age! Recommended for several reasons; prolonged sitting or standing, flying and travel, exercise and recovery, minor to moderate swelling or varicose veins.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
        {
            'name': 'ELEVATION COMPRESSION SOCKS',
            // 'old_price': '49.00',
            'price': '30.00',
            'quantity': '1',
            'rating': '4.5',
            'img': ['./src/pr_img/socks7.jpg'],
            'colors': ['Black', 'Navy'],
            'colors_data': ['blue', 'black'],
            'colors2': ['./src/img_colors/black7.jpg', './src/img_colors/navy7.jpg'],
            'size': ['M/L', 'L/XL'],
            'unable_size': [''],
            'product_description': 'These moderate compression socks will help improve circulation when you need or want extra support in your day at every age! Recommended for several reasons; prolonged sitting or standing, flying and travel, exercise and recovery, minor to moderate swelling or varicose veins.',
            'product_details': ['Constructed from our 5.0 oz. lightweight Tropical Twill stretch fabric', '4-pocket design includes two deep front pockets, two back pockets with button-through flap closure. A small zip section in the right front pocket is great for travel', 'Pleated styling', 'Non-roll stretch waistband', 'Narrow belt loops', '37" unfinished inseam is ready to be hemmed to your exact measurements', 'Wrinkle resistant 60% polyester, 37% cotton, 3% spandex', 'Machine wash', 'Imported',],
            'reviews': ['Great fabric, and it fits great, like the all the rest of Sportif pants. Sad that all Sportif Chinos are being discontinued. I can’t understand why.', 'Ordered size 44 waist. Actually measure slightly under.', 'Love them. Will wear often.']
        },
    ],
    'sale': []

}
// debugger
// adding product on sales
for (let i = 0; i < Object.values(products).length-1; i++) {
    for (let j = 0; j < Object.values(products)[i].length; j++) {
        if (Object.values(products)[i][j].old_price){
            products.sale.push(Object.values(products)[i][j])
        }
    }
}

let productsSizes = {
    'shorts': ['30', '32', '34', '36', '38', '40', '42', '44', '46', 'MED', 'LRG', 'XL', 'XLL'],
    'pants': ['28', '30', '32', '34', '36', '38', '40', '42', '44', '46', 'MED', 'LRG', 'XL', 'XLL'],
    'shirts': ['28', '30', '32', '34', '36', '38', '40', '42', '44', '46', 'MED', 'LRG', 'XL', 'XLL'],
    'accessories': ['28', '30', '32', '34', '36', '38', '40', '42', '44', '46', 'MED', 'LRG', 'XL', 'XLL', '1SZ', 'M/L', 'L/XL'],
    'sale': ['28', '30', '32', '34', '36', '38', '40', '42', '44', '46', 'MED', 'LRG', 'XL', 'XLL'],
}